name = "PublicRegistry"
uuid = "617be3c6-fb4e-4c21-9f42-abb8874174fd"
repo = "git@github.com:StevenWhitaker/PublicRegistry.git"
description = "A registry for public packages"

[packages]
85f1910e-5d62-11e9-1bce-2b30a05932d4 = { name = "PERK", path = "P/PERK" }
e905d6ce-5d58-11e9-2213-8b5d9f240645 = { name = "STFR", path = "S/STFR" }
